import Image from "next/image";
import { notFound } from "next/navigation";
import {
  CONTEXT_NOTE_CATEGORY_LABELS,
  INCLUSION_TYPE_LABELS,
  ledByLabel,
  REPRESENTATION_HANDLING_DEFINITIONS,
  REPRESENTATION_HANDLING_LABELS,
  THEME_LABELS,
} from "@latino-canon/core";
import { getTitle, posterUrl } from "@/lib/api";
import { Badge } from "@/components/ui/Badge";

export const dynamic = "force-dynamic";

export default async function TitlePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const title = await getTitle(id).catch(() => null);
  if (!title) notFound();

  // First-ordered director credit, same "primary director" pick db/cards.ts's
  // hydrateCards uses for TitleCard.directorGender - drives led_by's gendered label.
  const directorGender = title.credits.find((c) => c.role === "director")?.person.gender ?? null;

  return (
    <article className="grid grid-cols-1 gap-8 sm:grid-cols-[240px_1fr]">
      <div className="relative aspect-2/3 w-full overflow-hidden rounded-xl bg-surface-raised shadow-card">
        <Image src={posterUrl(title.posterKey)} alt="" fill sizes="240px" className="object-cover" priority />
      </div>
      <div>
        <div className="flex flex-wrap items-center gap-2.5">
          <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title.title}</h1>
          {title.yearStart >= 2026 && <Badge variant="solid">✨ New to Canon</Badge>}
          {title.oscarWin && <Badge variant="oscar" title={title.oscarWin}>🏆 {title.oscarWin}</Badge>}
        </div>
        <p className="mt-1 text-muted">
          {title.yearStart}
          {title.yearEnd ? `–${title.yearEnd}` : ""} · {title.kind} · {title.country.join(", ")}
        </p>

        {title.representationHandling && (
          <p className="mt-3 rounded-lg border-l-[3px] border-gold bg-gold/10 px-3 py-2 text-sm">
            {REPRESENTATION_HANDLING_LABELS[title.representationHandling]} —{" "}
            {REPRESENTATION_HANDLING_DEFINITIONS[title.representationHandling]}
          </p>
        )}

        <div className="mt-3 flex flex-wrap gap-1.5">
          {title.tags
            .filter((t) => t.kind === "inclusion_type")
            .map((t) => (
              <Badge key={t.slug} variant="inclusion" title={`${Math.round(t.confidence * 100)}% · ${t.source}`}>
                {t.slug === "led_by"
                  ? ledByLabel(directorGender)
                  : (INCLUSION_TYPE_LABELS[t.slug as keyof typeof INCLUSION_TYPE_LABELS] ?? t.label)}
              </Badge>
            ))}
          {title.tags
            .filter((t) => t.kind === "theme")
            .map((t) => (
              <Badge key={t.slug}>{THEME_LABELS[t.slug as keyof typeof THEME_LABELS] ?? t.label}</Badge>
            ))}
        </div>

        {(title.credits.length > 0 || Boolean(title.runtime)) && (
          <section className="mt-6 space-y-1.5 text-[0.9rem]">
            {title.credits.filter((c) => c.role === "creator" || c.role === "director").length > 0 && (
              <p>
                <strong>{title.credits.some((c) => c.role === "creator") ? "Created by" : "Directed by"}:</strong>{" "}
                {title.credits
                  .filter((c) => c.role === "creator" || c.role === "director")
                  .map((c) => c.person.name)
                  .join(", ")}
              </p>
            )}
            {title.credits.filter((c) => c.role === "cast").length > 0 && (
              <p>
                <strong>Starring:</strong>{" "}
                {title.credits
                  .filter((c) => c.role === "cast")
                  .slice(0, 6)
                  .map((c) => c.person.name)
                  .join(", ")}
              </p>
            )}
            {title.runtime ? (
              <p>
                <strong>Runtime:</strong> {title.runtime} min
              </p>
            ) : null}
          </section>
        )}

        {title.blurb && (
          <section className="mt-6">
            <h2 className="flex items-center gap-2 text-base font-semibold">
              Why it matters
              <Badge title={`Generated by ${title.blurb.model}, editor-approved`}>AI-assisted</Badge>
            </h2>
            <p className="mt-2 text-[0.95rem] leading-relaxed text-text/90">{title.blurb.text}</p>
            {title.blurb.sources.length > 0 && (
              <details className="mt-2">
                <summary className="cursor-pointer text-sm text-muted transition-colors hover:text-text">Sources</summary>
                <ul className="mt-1.5 space-y-1 text-sm text-muted">
                  {title.blurb.sources.map((s, i) => (
                    <li key={i}>
                      <strong className="text-text/80">{s.kind}</strong> — {s.quote ?? s.ref}
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </section>
        )}

        {title.synopsis && (
          <section className="mt-6">
            <h2 className="text-base font-semibold">Synopsis</h2>
            <p className="mt-2 text-[0.95rem] leading-relaxed text-text/90">{title.synopsis}</p>
          </section>
        )}

        {title.contextNotes.length > 0 && (
          <section className="mt-6">
            <h2 className="text-base font-semibold">Representation notes</h2>
            {title.contextNotes.map((note, i) => (
              <div key={i} className="mt-3">
                <Badge title={note.status === "review_required" ? "Still under editorial review" : "Confirmed"}>
                  {CONTEXT_NOTE_CATEGORY_LABELS[note.category]}
                </Badge>
                <p className="mt-1.5 text-[0.95rem] leading-relaxed text-text/90">{note.summary}</p>
                {note.sources.length > 0 && (
                  <details className="mt-1.5">
                    <summary className="cursor-pointer text-sm text-muted transition-colors hover:text-text">Sources</summary>
                    <ul className="mt-1.5 space-y-1 text-sm text-muted">
                      {note.sources.map((s, j) => (
                        <li key={j}>
                          <strong className="text-text/80">{s.kind}</strong> — {s.quote ?? s.ref}
                        </li>
                      ))}
                    </ul>
                  </details>
                )}
              </div>
            ))}
          </section>
        )}
      </div>
    </article>
  );
}
