import { notFound } from "next/navigation";
import {
  CONTEXT_NOTE_CATEGORY_LABELS,
  INCLUSION_TYPE_LABELS,
  REPRESENTATION_HANDLING_DEFINITIONS,
  REPRESENTATION_HANDLING_LABELS,
  THEME_LABELS,
} from "@latino-canon/core";
import { getTitle, posterUrl } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function TitlePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const title = await getTitle(id).catch(() => null);
  if (!title) notFound();

  return (
    <article style={{ display: "grid", gridTemplateColumns: "260px 1fr", gap: "2rem" }}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={posterUrl(title.posterKey)} alt="" style={{ width: "100%", borderRadius: 10 }} />
      <div>
        <h1 style={{ marginBottom: 0 }}>{title.title}</h1>
        <p style={{ color: "var(--muted)" }}>
          {title.yearStart}
          {title.yearEnd ? `–${title.yearEnd}` : ""} · {title.kind} · {title.country.join(", ")}
        </p>

        {title.representationHandling && (
          <p className="context-banner">
            {REPRESENTATION_HANDLING_LABELS[title.representationHandling]} —{" "}
            {REPRESENTATION_HANDLING_DEFINITIONS[title.representationHandling]}
          </p>
        )}

        <div className="tag-row">
          {title.tags
            .filter((t) => t.kind === "inclusion_type")
            .map((t) => (
              <span key={t.slug} className="tag inclusion" title={`${Math.round(t.confidence * 100)}% · ${t.source}`}>
                {INCLUSION_TYPE_LABELS[t.slug as keyof typeof INCLUSION_TYPE_LABELS] ?? t.label}
              </span>
            ))}
          {title.tags
            .filter((t) => t.kind === "theme")
            .map((t) => (
              <span key={t.slug} className="tag">
                {THEME_LABELS[t.slug as keyof typeof THEME_LABELS] ?? t.label}
              </span>
            ))}
        </div>

        {title.blurb && (
          <section style={{ marginTop: "1.5rem" }}>
            <h2 style={{ fontSize: "1rem" }}>
              Why it matters{" "}
              <span className="tag" title={`Generated by ${title.blurb.model}, editor-approved`}>
                AI-assisted
              </span>
            </h2>
            <p>{title.blurb.text}</p>
            {title.blurb.sources.length > 0 && (
              <details>
                <summary style={{ color: "var(--muted)", fontSize: "0.8rem" }}>Sources</summary>
                <ul style={{ color: "var(--muted)", fontSize: "0.8rem" }}>
                  {title.blurb.sources.map((s, i) => (
                    <li key={i}>
                      <strong>{s.kind}</strong> — {s.quote ?? s.ref}
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </section>
        )}

        {title.synopsis && (
          <section style={{ marginTop: "1.5rem" }}>
            <h2 style={{ fontSize: "1rem" }}>Synopsis</h2>
            <p>{title.synopsis}</p>
          </section>
        )}

        {title.contextNotes.length > 0 && (
          <section style={{ marginTop: "1.5rem" }}>
            <h2 style={{ fontSize: "1rem" }}>Representation notes</h2>
            {title.contextNotes.map((note, i) => (
              <div key={i} style={{ marginBottom: "1rem" }}>
                <p>
                  <span className="tag" title={note.status === "review_required" ? "Still under editorial review" : "Confirmed"}>
                    {CONTEXT_NOTE_CATEGORY_LABELS[note.category]}
                  </span>
                </p>
                <p>{note.summary}</p>
                {note.sources.length > 0 && (
                  <details>
                    <summary style={{ color: "var(--muted)", fontSize: "0.8rem" }}>Sources</summary>
                    <ul style={{ color: "var(--muted)", fontSize: "0.8rem" }}>
                      {note.sources.map((s, j) => (
                        <li key={j}>
                          <strong>{s.kind}</strong> — {s.quote ?? s.ref}
                        </li>
                      ))}
                    </ul>
                  </details>
                )}
              </div>
            ))}
          </section>
        )}
      </div>
    </article>
  );
}
